"""initial

Revision ID: 55003edece2d
Revises: 
Create Date: 2026-08-03 12:15:37.802419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55003edece2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('channel', sa.String(length=20), nullable=False, comment='投递渠道: boss/website/referral/liepin/other'))
    op.add_column('applications', sa.Column('follow_up_notes', sa.Text(), nullable=True, comment='跟进记录'))
    op.add_column('applications', sa.Column('interview_feedback', sa.Text(), nullable=True, comment='面试反馈原始文本'))
    op.add_column('applications', sa.Column('interview_key_points', sa.JSON(), nullable=True, comment='AI提取的面试关键点'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview_key_points')
    op.drop_column('applications', 'interview_feedback')
    op.drop_column('applications', 'follow_up_notes')
    op.drop_column('applications', 'channel')
    # ### end Alembic commands ###
